docs: add TLDR section
nvim-neorg/neorg pull request #1046
Opened 2023-09-04 07:37 UTC by champignoom

For neorg users that are not neovim devs or debuggers.

Hopefully this caps the counterproductivity of configuring for productivity.

2023-09-04 07:48 UTC, max397574 requested changes

2023-09-04 07:48 UTC, max397574 commented on README.md
> +1. Install [Meslo Nerd Font](https://github.com/ryanoasis/nerd-fonts/).
```suggestion
1. Install [Meslo Nerd Font](https://www.nerdfonts.com/font-downloads) or any other nerd font.
```

2023-09-04 07:48 UTC, max397574 commented on README.md
> +        ensure_installed = { "lua" },
```suggestion
        ensure_installed = { "lua", "norg" },
```
I'm not even sure if lua is still needed. Isn't it bundled in core now?

2023-09-04 07:48 UTC, max397574 commented on README.md
> +      },
```suggestion
        highlight = { enable = true },
      },
```

2023-09-04 07:48 UTC, max397574 commented on README.md
> +        ensure_installed = { "lua" },
nvim the norg, since we have the "sync-parsers" command

2023-09-04 07:58 UTC, champignoom commented on README.md
> +1. Install [Meslo Nerd Font](https://github.com/ryanoasis/nerd-fonts/).
The github page loads faster and looks more instructive.

The reason that I put one particular font here is that people might struggle with figuring out the exact character sequence to put in ther config file (here it's "MesloLGM Nerd Font Mono"). For those who actually have a preference outside Meslo, it should be self-evident anyway that Meslo isn't the only choice.

2023-09-04 08:02 UTC, champignoom commented on README.md
> +        ensure_installed = { "lua" },
Isn't sync-parsers taking care of norg parser already?

If not, I guess we also need norg_meta.

I'm not sure if lua is need. `opts = {}` is probably all we need ?

2023-09-04 09:06 UTC, max397574 approved these changes

2023-09-04 10:00 UTC, max397574 commented on README.md
> +3. Make sure you have git.
users who don't realize that they should have git also perhaps don't know if they have it or not
```suggestion
3. Make sure you have git by running `git --version`
```

2023-09-04 10:03 UTC, max397574 commented
forgot the `.` sorry😅

2023-09-08 17:03 UTC, champignoom commented
A minimal working configuration like this has been [proved](https://github.com/nvim-neorg/neorg/issues/1050#issuecomment-1705902049) to be effective for debugging as well.

2023-09-15 12:41 UTC, merged