Update docs
nvim-neorg/neorg pull request #1098
Opened 2023-09-26 04:15 UTC by leongjs98

Just changing the documentation

2023-09-26 05:28 UTC, max397574 commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
neogen is just used for annotations of functions

2023-09-26 05:31 UTC, max397574 requested changes

2023-09-26 05:31 UTC, max397574 commented on lua/neorg/modules/core/qol/todo_items/module.lua
> +    -- or what have you) will convert the non-todo item into one:
1. I'm not even sure if this is correct English, it sounds very weird to me (I'm not a native speaker though)
2. I'd just write "or another keybinding to change todo states"

2023-09-26 06:13 UTC, leongjs98 commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
OK, I read through neogen README and understand neogen is just for function annotations

I guess my confusion came from this line
https://github.com/nvim-neorg/neorg/blob/main/docs/CONTRIBUTING.md?plain=1#L39
```
- **Please** comment all your code! Documentation for functions is generated by [neogen](https://github.com/danymat/neogen).
```

When I first read it, I thought the documentation meant the auto-generated wiki
But it actually meant annotations/explanations of the code (which is then
auto-generated into wiki pages)

should we change it as such?

```diff
- **Please** comment all your code! *Documentation* for functions is generated by [neogen](https://github.com/danymat/neogen).
+ **Please** comment all your code! *Annotations* for functions is generated by [neogen](https://github.com/danymat/neogen).
```

2023-09-26 06:18 UTC, max397574 commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
yes ig you could do that
even though it would be clear if you look at neogen ig

2023-09-26 06:22 UTC, vhyrro commented on lua/neorg/modules/core/qol/todo_items/module.lua
> +    -- or what have you) will convert the non-todo item into one:
This change is just fine. It's valid english haha

2023-09-26 06:23 UTC, vhyrro commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
```diff
- **Please** comment all your code! *Documentation* for functions is generated by [neogen](https://github.com/danymat/neogen).
+ **Please** comment all your code! *Annotations* for functions are generated by [neogen](https://github.com/danymat/neogen).
```

Make sure to switch up the `is` to `are` and yup this seems like a good change to me!

2023-09-26 06:30 UTC, max397574 commented on lua/neorg/modules/core/qol/todo_items/module.lua
> +    -- or what have you) will convert the non-todo item into one:
😳 ok then
but I still think you could add what I said

2023-09-26 06:32 UTC, leongjs98 commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
```suggestion
The documentations (wiki pages) are generated based on the comments in the code.
And all the settings in generating the wiki are in `docgen/`

To generate documentations locally, run `make local-documentation`. See
`Makefile` for more details If there's no error, you should then see a `wiki/`
folder.

```

With neogen confusion cleared out, how about this?

2023-09-26 06:53 UTC, leongjs98 commented on lua/neorg/modules/core/qol/todo_items/module.lua
> +    -- or what have you) will convert the non-todo item into one:
I believe it's correct. But to make it clearer to even non native English speaker
how about this?

```suggestion
-- or what have you) will convert the non-todo item into one:
++ or your custom keybind) will convert the non-todo item into one:
```

2023-09-26 06:55 UTC, max397574 commented on lua/neorg/modules/core/qol/todo_items/module.lua
> +    -- or what have you) will convert the non-todo item into one:
well like this you could think that it's just about the cycle thing or however the `<c-space>` is called
but it's also for `<localleader>td|p|u|c` etc

2023-09-26 11:12 UTC, leongjs98 commented on lua/neorg/modules/core/qol/todo_items/module.lua
> +    -- or what have you) will convert the non-todo item into one:
I will just stick with "what have you"

2023-09-26 11:20 UTC, leongjs98 commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
> yes ig you could do that even though it would be clear if you look at neogen ig

It's best to assume the newcomer reading the docs could misunderstand even after going through neogen README just like I did.
So having the documentation as clear as possible would be the best for everyone :)

2023-09-26 11:35 UTC, max397574 requested changes

2023-09-26 11:35 UTC, max397574 commented on docs/CONTRIBUTING.md
> +- **Please** comment all your code! Annotations for functions are generated by [neogen](https://github.com/danymat/neogen).
```suggestion
- **Please** comment all your code! Annotations for functions can be generated with [neogen](https://github.com/danymat/neogen).
```

2023-09-26 11:35 UTC, max397574 commented on docs/CONTRIBUTING.md
> +The documentations (wiki pages) are generated based on the comments in the code. And all the settings in generating the wiki are in [`docgen/`](../docgen/).
```suggestion
The documentations (wiki pages) are generated based on the comments in the code. All the logic for generating the wiki is in [`docgen/`](../docgen/).
```

2023-09-26 11:35 UTC, max397574 commented on docs/CONTRIBUTING.md
> +To generate documentations locally, run `make local-documentation` (see `Makefile` for more details). If there's no error, you should then see a `wiki/` folder generated.
```suggestion
To generate documentations locally, run `make local-documentation` (see [`Makefile`](../Makefile) for more details). If there's no error, you should then see a `wiki/` folder generated.
```

2023-09-26 11:35 UTC, max397574 commented on docs/CONTRIBUTING.md
> +If you feel like improving the documentation, please make changes to the corresponding comments in the correct file. For example, to make changes to the `core.qol.todo_items` documentation, please ma
```suggestion
If you want to work on the documentation, please make changes to the corresponding comments in the correct file. For example, to make changes to the `core.qol.todo_items` documentation, please make changes to the comments in [`./lua/neorg/modules/core/qol/todo_items/module.lua`](../lua/neorg/modules/core/qol/todo_items/module.lua)
```

2023-09-26 11:47 UTC, danymat commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
> It's best to assume the newcomer reading the docs could misunderstand even after going through neogen README just like I did.

Do not hesitate to tell me if neogen README is not clear enough, and what do you think could be added/changed in order to improve it :)

2023-10-03 06:21 UTC, leongjs98 commented on docs/CONTRIBUTING.md
> +Like mentioned above, the documentation (wiki) is generated via [neogen](https://github.com/danymat/neogen) using comments in the code.
> Do not hesitate to tell me if neogen README is not clear enough, and what do you think could be added/changed in order to improve it :)

It was the Neorg CONTRIBUTING.md that confused me, the Neogen README is fine for the most part
but sure! I will let you know if there's anything I think that can be improved

2023-10-04 14:58 UTC, merged