Clarify font requirments in the README
nvim-neorg/neorg pull request #1245
Opened 2023-12-22 11:30 UTC by refaelsh

This PR clarifies font requirements in the README. Please see this discussion: https://github.com/nvim-neorg/neorg/discussions/1243.

2023-12-23 13:21 UTC, champignoom requested changes

2023-12-23 13:21 UTC, champignoom commented on README.md
> +2. Set your terminal font to the Nerd font you installed in the previous step.
```suggestion
2. Set your terminal font to the monospace variant of that font, for example "MesloLGM Nerd Font Mono".
```

The sample font name "MesloLGM Nerd Font Mono" should be kept here so that the user doesn't have to research on trivial things like that peculiar font name, which is the point of TL;DR.

2023-12-23 13:25 UTC, max397574 commented on README.md
> +1. Install one of the Nerd fonts, for example: [Meslo Nerd Font](https://github.com/ryanoasis/nerd-fonts/).
@refaelsh why mark this as resolved?

2023-12-23 15:59 UTC, refaelsh commented on README.md
> +1. Install one of the Nerd fonts, for example: [Meslo Nerd Font](https://github.com/ryanoasis/nerd-fonts/).
> @refaelsh why mark this as resolved?

I am sorry. What I mean is: "I agree with your proposed changes, they are better than mine".
I am not yet proficient with PR system in GitHub. At work with use something else.

2023-12-23 16:58 UTC, max397574 commented on README.md
> +1. Install one of the Nerd fonts, for example: [Meslo Nerd Font](https://github.com/ryanoasis/nerd-fonts/).
well then you could actually apply the changes 😄

2023-12-26 14:52 UTC, vhyrro commented
lgtm, thanks!

2023-12-26 14:53 UTC, merged