More calendar UI mappings
nvim-neorg/neorg pull request #1483
Opened 2024-06-26 01:07 UTC by benlubas

closes #1340 

Notably, the suggested `g` in that is now `d` and the suggested `t/T` is now `g/G` b/c `t` is already taken.

2024-06-26 01:08 UTC, benlubas commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +                        { "<Esc>",             "@namespace" },
all of this is stylua being weird. I'm not sure why

2024-06-26 01:09 UTC, benlubas commented
I also didn't add all the mappings to the help thing yet. I can do that tomorrow

2024-06-26 01:09 UTC, benlubas commented
@simonhughxyz feedback/testing would be appreciated!

2024-06-26 08:55 UTC, vhyrro reviewed
Great work on this, left some comments.

2024-06-26 08:55 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +            end
suggestion: replace with `vim.v.count1` which does the same thing

2024-06-26 08:55 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +        })[((month - 1) % 12) + 1]
nitpick(non-blocking): maybe extract this out to a variable like `wrapped_month` so that the intent is clearer?

Would be even better if a comment was added that the arithmetic is done to account for 1-based indexing.

2024-06-26 08:55 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +                new_date.day = new_date.day - (lib.number_wrap(new_date.wday - 1, 1, 7) - 1)
praise: good job using `lib.number_wrap` for this one, very clean :)

2024-06-26 08:55 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +                print("last_semi_jump:", last_semi_jump)
todo: remove this debug statement :p

2024-06-26 08:55 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +                local thousends = math.floor(date.year / 1000) * 1000
nitpick: `thousends` -> `thousands`

2024-06-26 08:55 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +                local thousends = math.floor(date.year / 1000) * 1000
nitpick: `thousends` -> `thousands`

2024-06-26 09:23 UTC, vhyrro commented
issue: I've noticed that `e` skips the current month and goes straight to the end of the next month. Another thing to fix :)

2024-06-26 13:50 UTC, benlubas commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +        })[((month - 1) % 12) + 1]
will switch to number wrap, I wrote this part before I was aware of that lib function

2024-06-26 17:03 UTC, max397574 requested changes

2024-06-26 17:03 UTC, max397574 commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
> +                local one = vim.fn.getcharstr()
why not just make the mappings `<count>g` and then use `vim.v.count` instead of this?
would make much more sense
also wouldn't force the user to do `01` instead of `1`

2024-06-26 21:04 UTC, benlubas commented
Have updated with the latest from our discussion on discord and feedback above. TL;DR:
- `<count>g` instead of `g<count>`
	- same for `d`
- g/G deal with month days in the monthly view
- g -> 1st of the month
- G -> last of the month
- `c/C` is completely gone b/c it's out of place in the monthly view

This also adds `winfixbuf` for the help windows and the calendar buffer itself.

2024-06-27 11:29 UTC, vhyrro requested changes
Rest of code looks great now, just some finishing touches.

2024-06-27 11:33 UTC, vhyrro commented on lua/neorg/modules/core/ui/calendar/views/monthly.lua
>              end, { buffer = ui_info.buffer })
nitpick: also set `d` to `nowait` so that it doesn't stall :)

2024-06-27 13:27 UTC, vhyrro approved these changes

2024-06-27 13:27 UTC, merged

2024-12-18 18:25 UTC, turkishfilms commented
Is there a reason we can't set our own bindings? I am going to get into neorg dev soon i want to help build this.