fix comment
nvim-neorg/neorg pull request #1567
Opened 2024-09-01 20:37 UTC by krmpotic

fixes documentation of https://github.com/nvim-neorg/neorg/wiki/Summary
by removing a leftover comment

2024-09-01 21:57 UTC, benlubas requested changes

2024-09-01 21:57 UTC, benlubas commented on lua/neorg/modules/core/summary/module.lua
>      -- - "by_path" - Similar to "default" but uses the capitalized name of the folder containing a *.norg file as category.
We should make it clear that the user can provide a function, something like:
```suggestion
    -- - "by_path" - Similar to "default" but uses the capitalized name of the folder containing a *.norg file as category.
    -- A custom function with the signature: `fun(files: PathlibPath[], ws_root: PathlibPath,
    -- heading_level: number?, include_categories: string[]?): string[]?`. Returning a list of lines
    -- that make up the summary
```

2024-09-02 20:48 UTC, krmpotic commented
changed as suggested

2024-09-02 21:44 UTC, benlubas approved these changes

2024-09-02 22:15 UTC, merged