feat(esupports.hop): Add tab drop as option for open_mode
nvim-neorg/neorg pull request #1580
Opened 2024-09-13 16:49 UTC by devansh08

This adds `:tab drop` as an option for opening a file when clicking a file link. Tab drop as an option would be helpful to avoid opening a file a new tab, when it has already been open somewhere else.

IMO, this could be a replacement for the `tabnew` option itself, as tab drop will open a new tab normally if the same file is already not open. But it can be kept as a separate option as well. Also IMO, never bad to have multiple options :)

Do let me know your thoughts on this. If this looks good and needs any documenting, happy to work on that as well.

Thanks!

2024-11-01 05:06 UTC, devansh08 commented on lua/neorg/modules/core/esupports/hop/module.lua
> +                        if open_mode ~= "tab-drop" then
Fixed now

2024-11-01 05:11 UTC, devansh08 commented
@benlubas Fixed the mentioned issue and added docs.
I accidentally broke my git while trying to rebase, so had to commit my changes again. My bad!

Let me know if the docs part is good. Could not think of any better keybind using CR, so went with C-t. Let me know if you have any better ideas for that.

Thanks!

2024-11-01 07:30 UTC, devansh08 commented
I've just added another similar option that uses `:drop` instead. This works similar to `tab-drop` but would be useful for a buffer focused workflow (to which I have recently switched over :)). So cases where you have the destination already open in a split, it would just navigate to that instead of opening the destination in the current buffer (what default `hop` does today).

Let me know your thoughts. Thanks!

2024-11-09 19:13 UTC, benlubas requested changes
Docs look good, but we can't override `<C-d>` that's a default vim bind.

2024-11-09 19:13 UTC, benlubas commented on lua/neorg/modules/core/keybinds/module.lua
> +                        "<C-d>",
`<c-d>` is the keybind to scroll down half a page. It's incredibly widely used, so this is not an acceptable default.

I'd say this doesn't have to have a default binding.

2024-11-09 19:31 UTC, devansh08 commented on lua/neorg/modules/core/keybinds/module.lua
> +                        "<C-d>",
I use `<C-d>` and I completely forgot about it when writing this :smile:
Sure, will remove it from the defaults.

2024-11-09 19:56 UTC, devansh08 commented on lua/neorg/modules/core/keybinds/module.lua
> +                        "<C-d>",
Done

2024-11-10 21:15 UTC, benlubas commented on lua/neorg/modules/core/keybinds/module.lua
> +                    {
Okay wait I'm so sorry, but `<c-t>` is a builtin tag list keybind, it takes you back to the previous spot in the tag list. I totally forgot about that. @devansh08

2024-11-11 16:07 UTC, devansh08 commented on lua/neorg/modules/core/keybinds/module.lua
> +                    {
Ah no worries. I did not realize it either.
Would something like `<M-t>` be fine ? Don't see that keybind do anything in base neovim normal mode. I'm kinda running out of logical keybinds to use :sweat_smile:

2024-11-14 03:03 UTC, benlubas commented on lua/neorg/modules/core/keybinds/module.lua
> +                    {
yeah that would be fine, I don't think that neovim binds anything to alt by default b/c default terminals don't interpret it.

2024-11-14 03:39 UTC, devansh08 commented on lua/neorg/modules/core/keybinds/module.lua
> +                    {
Done :+1:

2024-11-16 20:17 UTC, benlubas approved these changes

2024-11-16 20:18 UTC, merged