fix: add coq_nvim completion integration
nvim-neorg/neorg pull request #1597
Opened 2024-10-20 21:55 UTC by TheLeoP

Fixes #1594

2024-10-27 15:04 UTC, benlubas requested changes
I have no way to easily test this. I trust that the heart reaction means that it worked.

Just a few lines to remove and then I will merge

2024-10-27 15:04 UTC, benlubas commented on lua/neorg/modules/core/integrations/coq_nvim/module.lua
> +                    start_offset = nil,
What is the point of setting a key to nil here? In lua this is the same as not including the key at all

2024-10-27 15:07 UTC, LoCrealloc commented
the heart reaction meant something like "great that someone is putting effort into this", i did not test this pull request (yet)

2024-10-27 16:30 UTC, TheLeoP commented on lua/neorg/modules/core/integrations/coq_nvim/module.lua
> +                    start_offset = nil,
I left them there for future reference.

As far as i can tell, there is no formal definition/interface for what the completion context should have. When i originally added support for coq, I missed a lot of fields (and the type inference of lua-ls didn't help (because of how the modules are structured, I think. I didn't look into it).

For this PR i had to look into both nvim-cmp and nvim-compe source code to know what fields a context is supposed to have and what the value of each one is supposed to be. Not all of the context's fields were currently being used by neorg, but since the current implementation seems tightly coupled with what nvim-compe consideres a context I thought leaving them here will help with future changes (removing the need to check nvim-compe and nvim-cmp codebases)

2024-10-28 11:04 UTC, benlubas commented
Oh, please test when you get the chance and let me know.

2024-10-29 17:27 UTC, LoCrealloc commented
@benlubas just tested the changes and as far as I can tell the problem is solved - no  error messages anymore

2024-10-31 00:15 UTC, benlubas commented on lua/neorg/modules/core/integrations/coq_nvim/module.lua
> +                    start_offset = nil,
fair enough

2024-10-31 00:15 UTC, benlubas approved these changes

2024-10-31 00:16 UTC, merged