fix: Tangle should close fd for files
nvim-neorg/neorg pull request #1618
Opened 2024-12-15 03:36 UTC by Jimmyscene

The current implementation keeps the fd open for each file it is tangling, which results in tangled shell scripts not being able to be run until the instance is closed

2024-12-15 03:36 UTC, Jimmyscene commented
Small fix, but let me know if there's anything I should update :)

2025-02-05 22:59 UTC, benlubas requested changes

2025-02-05 22:59 UTC, benlubas commented on lua/neorg/modules/core/tangle/module.lua
> +                vim.loop.fs_close(fd)
`vim.loop` -> `vim.uv`

see `:h vim.loop`

2025-02-06 03:32 UTC, benlubas approved these changes

2025-02-06 22:12 UTC, merged